In [16]:
import pandas as pd
import numpy as np

### 자료출처
 - 지역별 수온온도 : 기상청(https://data.kma.go.kr/data/sea/selectBuoyRltmList.do?pgmNo=52)

In [29]:
shinan_df=pd.read_csv('./data/temperature/신안 통합.csv',encoding='cp949',index_col='일시')
df1=shinan_df.iloc[:,1:].groupby('일시').mean()
df1['지점']=22183
df1.to_csv('./data/temperature/month/신안_월별.csv')

         평균 풍속(m/s)    평균기압(hPa)  평균 상대습도(%)  평균 기온(°C)  평균 수온(°C)     지점
일시
2013-06    1.788889  1007.111111   89.666667  20.444444  19.233333  22183
2013-07    3.879310  1007.239286   91.310345  23.758621  21.734483  22183
2013-08    2.593548  1007.761290   88.258065  25.764516  24.564516  22183
2013-09    3.583333  1014.803333   78.433333  22.166667  21.816667  22183
2013-10    4.900000  1019.766667   73.483871  17.641935  19.064516  22183
...             ...          ...         ...        ...        ...    ...
2023-10    4.574194  1019.225806   72.903226  19.093548  21.090323  22183
2023-11    6.166667  1022.193333   73.033333  12.180000  16.143333  22183
2023-12    5.223077  1024.650000   77.076923   6.823077  11.396154  22183
2024-01    5.536667  1024.896667   68.600000   4.880000   8.346667  22183
2024-02    4.882759  1023.362069   73.620690   6.531034   7.986207  22183

[129 rows x 6 columns]

In [18]:
geoje_df=pd.read_csv('./data/temperature/거문도 통합.csv',encoding='cp949',index_col='일시')
df2=geoje_df.iloc[:,1:].groupby('일시').mean()
df2['지점']=22103
df2.to_csv('./data/temperature/month/거문도_월별.csv')

In [19]:
geoje_df=pd.read_csv('./data/temperature/거제도 통합.csv',encoding='cp949',index_col='일시')
df3=geoje_df.iloc[:,1:].groupby('일시').mean()
df3['지점']=22104
df3.to_csv('./data/temperature/month/거제도_월별.csv')

In [20]:
ulsan_df=pd.read_csv('./data/temperature/울산 통합.csv',encoding='cp949')
df4=ulsan_df.iloc[:,1:].groupby('일시').mean()
df4['지점']=22189
df4.to_csv('./data/temperature/month/울산_월별.csv')

In [21]:
df1.corr()

,평균 풍속(m/s),평균기압(hPa),평균 상대습도(%),평균 기온(°C),평균 수온(°C),평균 최대 파고(m),평균 유의 파고(m),최고 유의 파고(m),최고 최대 파고(m),평균 파주기(sec),최고 파주기(sec),지점
평균 풍속(m/s),1.000000,0.859587,-0.794749,-0.767319,-0.658459,0.856453,0.860826,0.894204,0.790978,-0.052846,-0.012618,NaN
평균기압(hPa),0.859587,1.000000,-0.888791,-0.892999,-0.792991,0.785051,0.847756,0.890034,0.747366,-0.052048,-0.027577,NaN
평균 상대습도(%),-0.794749,-0.888791,1.000000,0.774605,0.663610,-0.783351,-0.743378,-0.815028,-0.719091,-0.078998,-0.127190,NaN
평균 기온(°C),-0.767319,-0.892999,0.774605,1.000000,0.972685,-0.716993,-0.749145,-0.793323,-0.645654,-0.020953,-0.040283,NaN
평균 수온(°C),-0.658459,-0.792991,0.663610,0.972685,1.000000,-0.590045,-0.633237,-0.672309,-0.518094,-0.044951,-0.043494,NaN
평균 최대 파고(m),0.856453,0.785051,-0.783351,-0.716993,-0.590045,1.000000,0.780304,0.863176,0.875332,0.042204,0.113118,NaN
평균 유의 파고(m),0.860826,0.847756,-0.743378,-0.749145,-0.633237,0.780304,1.000000,0.958970,0.760869,-0.288174,-0.270652,NaN
최고 유의 파고(m),0.894204,0.890034,-0.815028,-0.793323,-0.672309,0.863176,0.958970,1.000000,0.839988,-0.146393,-0.123406,NaN
최고 최대 파고(m),0.790978,0.747366,-0.719091,-0.645654,-0.518094,0.875332,0.760869,0.839988,1.000000,-0.103852,-0.039039,NaN
평균 파주기(sec),-0.052846,-0.052048,-0.078998,-0.020953,-0.044951,0.042204,-0.288174,-0.146393,-0.103852,1.000000,0.959722,NaN
최고 파주기(sec),-0.012618,-0.027577,-0.127190,-0.040283,-0.043494,0.113118,-0.270652,-0.123406,-0.039039,0.959722,1.000000,NaN
지점,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df2.corr()

,평균 풍속(m/s),평균기압(hPa),평균 상대습도(%),평균 기온(°C),평균 수온(°C),평균 최대 파고(m),평균 유의 파고(m),최고 유의 파고(m),최고 최대 파고(m),평균 파주기(sec),최고 파주기(sec),지점
평균 풍속(m/s),1.000000,0.711025,-0.558340,-0.606831,-0.422434,0.340558,0.189446,0.220389,0.360417,0.080307,0.115870,NaN
평균기압(hPa),0.711025,1.000000,-0.695306,-0.783227,-0.613100,-0.064246,-0.063418,-0.043076,-0.019350,0.058186,0.127891,NaN
평균 상대습도(%),-0.558340,-0.695306,1.000000,0.677654,0.466099,0.056178,0.066846,0.041422,-0.010745,-0.101273,-0.156205,NaN
평균 기온(°C),-0.606831,-0.783227,0.677654,1.000000,0.909417,0.034083,0.008270,-0.020637,-0.029451,0.038929,-0.088121,NaN
평균 수온(°C),-0.422434,-0.613100,0.466099,0.909417,1.000000,0.114587,0.032647,-0.000948,0.043160,0.126457,-0.017436,NaN
평균 최대 파고(m),0.340558,-0.064246,0.056178,0.034083,0.114587,1.000000,0.700651,0.734133,0.954673,-0.269540,-0.193821,NaN
평균 유의 파고(m),0.189446,-0.063418,0.066846,0.008270,0.032647,0.700651,1.000000,0.975709,0.629419,-0.632166,-0.726721,NaN
최고 유의 파고(m),0.220389,-0.043076,0.041422,-0.020637,-0.000948,0.734133,0.975709,1.000000,0.714541,-0.586382,-0.669376,NaN
최고 최대 파고(m),0.360417,-0.019350,-0.010745,-0.029451,0.043160,0.954673,0.629419,0.714541,1.000000,-0.200744,-0.114099,NaN
평균 파주기(sec),0.080307,0.058186,-0.101273,0.038929,0.126457,-0.269540,-0.632166,-0.586382,-0.200744,1.000000,0.853440,NaN
최고 파주기(sec),0.115870,0.127891,-0.156205,-0.088121,-0.017436,-0.193821,-0.726721,-0.669376,-0.114099,0.853440,1.000000,NaN
지점,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df3.corr()

,평균 풍속(m/s),평균기압(hPa),평균 상대습도(%),평균 기온(°C),평균 수온(°C),평균 최대 파고(m),평균 유의 파고(m),최고 유의 파고(m),최고 최대 파고(m),평균 파주기(sec),최고 파주기(sec),지점
평균 풍속(m/s),1.000000,0.460749,-0.448086,-0.341107,-0.188440,0.730477,0.355379,0.337180,0.680752,0.064631,0.088317,NaN
평균기압(hPa),0.460749,1.000000,-0.903674,-0.831105,-0.586339,0.113213,0.104105,0.100084,0.118528,-0.121021,-0.070839,NaN
평균 상대습도(%),-0.448086,-0.903674,1.000000,0.801270,0.536902,-0.092172,-0.107468,-0.118241,-0.113294,0.157277,0.125456,NaN
평균 기온(°C),-0.341107,-0.831105,0.801270,1.000000,0.869319,0.006280,0.031510,0.027277,-0.013455,0.090510,0.022603,NaN
평균 수온(°C),-0.188440,-0.586339,0.536902,0.869319,1.000000,0.080005,0.117687,0.092972,0.034216,0.030186,-0.043179,NaN
평균 최대 파고(m),0.730477,0.113213,-0.092172,0.006280,0.080005,1.000000,0.638549,0.636041,0.954293,0.030596,-0.019680,NaN
평균 유의 파고(m),0.355379,0.104105,-0.107468,0.031510,0.117687,0.638549,1.000000,0.978956,0.589309,-0.393575,-0.526085,NaN
최고 유의 파고(m),0.337180,0.100084,-0.118241,0.027277,0.092972,0.636041,0.978956,1.000000,0.648919,-0.386401,-0.505534,NaN
최고 최대 파고(m),0.680752,0.118528,-0.113294,-0.013455,0.034216,0.954293,0.589309,0.648919,1.000000,0.030724,-0.002734,NaN
평균 파주기(sec),0.064631,-0.121021,0.157277,0.090510,0.030186,0.030596,-0.393575,-0.386401,0.030724,1.000000,0.949223,NaN
최고 파주기(sec),0.088317,-0.070839,0.125456,0.022603,-0.043179,-0.019680,-0.526085,-0.505534,-0.002734,0.949223,1.000000,NaN
지점,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df4.corr()

,평균 풍속(m/s),평균기압(hPa),평균 상대습도(%),평균 기온(°C),평균 수온(°C),평균 최대 파고(m),평균 유의 파고(m),최고 유의 파고(m),최고 최대 파고(m),평균 파주기(sec),최고 파주기(sec),지점
평균 풍속(m/s),1.000000,0.473623,-0.397007,-0.467204,-0.382213,0.771229,0.775048,0.769734,0.753249,0.323226,0.181890,NaN
평균기압(hPa),0.473623,1.000000,-0.911193,-0.838055,-0.645527,0.649567,0.634824,0.617916,0.636514,0.521557,0.367717,NaN
평균 상대습도(%),-0.397007,-0.911193,1.000000,0.813864,0.619075,-0.570774,-0.548719,-0.529975,-0.547749,-0.523700,-0.325874,NaN
평균 기온(°C),-0.467204,-0.838055,0.813864,1.000000,0.899463,-0.561647,-0.546688,-0.525748,-0.543118,-0.382429,-0.218121,NaN
평균 수온(°C),-0.382213,-0.645527,0.619075,0.899463,1.000000,-0.382455,-0.368080,-0.380185,-0.391324,-0.252612,-0.148910,NaN
평균 최대 파고(m),0.771229,0.649567,-0.570774,-0.561647,-0.382455,1.000000,0.993195,0.978689,0.977598,0.666887,0.480095,NaN
평균 유의 파고(m),0.775048,0.634824,-0.548719,-0.546688,-0.368080,0.993195,1.000000,0.981629,0.962291,0.648109,0.439560,NaN
최고 유의 파고(m),0.769734,0.617916,-0.529975,-0.525748,-0.380185,0.978689,0.981629,1.000000,0.980739,0.617924,0.429695,NaN
최고 최대 파고(m),0.753249,0.636514,-0.547749,-0.543118,-0.391324,0.977598,0.962291,0.980739,1.000000,0.609783,0.485710,NaN
평균 파주기(sec),0.323226,0.521557,-0.523700,-0.382429,-0.252612,0.666887,0.648109,0.617924,0.609783,1.000000,0.817875,NaN
최고 파주기(sec),0.181890,0.367717,-0.325874,-0.218121,-0.148910,0.480095,0.439560,0.429695,0.485710,0.817875,1.000000,NaN
지점,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN